Repository cmu-delphi/covidcast-indicators, pull requests merged in 2020-10, with the labels that each got.

#378 Update safegraph patterns docstrings to pass pydocstyle
  safegraph_patterns/delphi_safegraph_patterns/process.py
  safegraph_patterns/delphi_safegraph_patterns/run.py
Labels: documentation

#352 CHC SFTP Downloads
  changehc/delphi_changehc/config.py
  changehc/delphi_changehc/constants.py
  changehc/delphi_changehc/download_ftp_files.py
  changehc/delphi_changehc/run.py
  changehc/delphi_changehc/sensor.py
  changehc/delphi_changehc/update_sensor.py
  changehc/params.json.template
  changehc/setup.py
  changehc/tests/params.json.template
  changehc/tests/test_download_ftp_files.py
  changehc/tests/test_update_sensor.py
Labels: API addition

#376 Update nchs docstrings to pass pydocstyle
  nchs_mortality/delphi_nchs_mortality/export.py
  nchs_mortality/delphi_nchs_mortality/pull.py
  nchs_mortality/delphi_nchs_mortality/run.py
Labels: documentation

#313 Refactor safegraph to use geo utils
  safegraph/delphi_safegraph/__init__.py
  safegraph/delphi_safegraph/geo.py
  safegraph/delphi_safegraph/process.py
Labels: blocked

#316 Refactor usafacts to use geo utils
  usafacts/delphi_usafacts/geo.py
  usafacts/delphi_usafacts/pull.py
  usafacts/delphi_usafacts/run.py
  usafacts/tests/test_geo.py
  usafacts/tests/test_pull.py
Labels: blocked
