Repository cmu-delphi/covidcast-indicators, pull requests merged in 2020-11, with the labels that each got.

#390 Remove unneeded try/except block
  jhu/tests/compare_receiving.py
Labels: blocked

#373 Update safegraph docstrings to pass pydocstyle
  safegraph/delphi_safegraph/process.py
  safegraph/delphi_safegraph/run.py
Labels: documentation

#374 Update cdccovidnet docstrings to pass pydocstyle
  cdc_covidnet/delphi_cdc_covidnet/api_config.py
  cdc_covidnet/delphi_cdc_covidnet/constants.py
  cdc_covidnet/delphi_cdc_covidnet/covidnet.py
  cdc_covidnet/delphi_cdc_covidnet/run.py
  cdc_covidnet/delphi_cdc_covidnet/update_sensor.py
Labels: documentation

#375 Update combo cases docstrings to pass pydocstyle
  combo_cases_and_deaths/delphi_combo_cases_and_deaths/constants.py
  combo_cases_and_deaths/delphi_combo_cases_and_deaths/run.py
Labels: documentation

#377 Update usafacts docstrings to pass pydocstyle
  usafacts/delphi_usafacts/geo.py
  usafacts/delphi_usafacts/pull.py
  usafacts/delphi_usafacts/smooth.py
Labels: blocked, documentation

#360 Update JHU docs to link to up to date exceptions
  jhu/DETAILS.md
Labels: documentation

#379 Update claims hosp docstrings to pass pydocstyle
  claims_hosp/delphi_claims_hosp/config.py
  claims_hosp/delphi_claims_hosp/indicator.py
  claims_hosp/delphi_claims_hosp/run.py
  claims_hosp/delphi_claims_hosp/smooth.py
  claims_hosp/delphi_claims_hosp/update_indicator.py
  claims_hosp/delphi_claims_hosp/weekday.py
Labels: documentation

#431 Refactor CHC to use smoothing utils
  changehc/delphi_changehc/__init__.py
  changehc/delphi_changehc/sensor.py
  changehc/delphi_changehc/smooth.py
  changehc/tests/test_sensor.py
  changehc/tests/test_smooth.py
Labels: blocked
