Repository cmu-delphi/covidcast-indicators, pull requests merged in 2021-07, with the labels that each got.

#1090 Standardization of Completed logging
  changehc/delphi_changehc/run.py
  changehc/delphi_changehc/update_sensor.py
  covid_act_now/delphi_covid_act_now/run.py
  hhs_facilities/delphi_hhs_facilities/run.py
  hhs_hosp/delphi_hhs/run.py
  nchs_mortality/delphi_nchs_mortality/export.py
  nchs_mortality/delphi_nchs_mortality/run.py
  quidel_covidtest/delphi_quidel_covidtest/run.py
  safegraph_patterns/delphi_safegraph_patterns/process.py
  safegraph_patterns/delphi_safegraph_patterns/run.py
Labels: enhancement

#1096 fix: sync version for bumpversion
  _delphi_utils_python/.bumpversion.cfg
Labels: chore

#1107 chore: sync prod->main
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
Labels: chore

#1126 chore: sync prod->main
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
Labels: chore

#1127 Add missing sources to sirCAL
  ansible/templates/sir_complainsalot-params-prod.json.j2
  sir_complainsalot/params.json.template
Labels: data quality

#1139 chore: sync prod->main
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
Labels: chore

#1144 chore: sync prod->main
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
Labels: chore

#1152 chore: sync prod->main
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
Labels: chore
