Repository cmu-delphi/covidcast-indicators, pull requests merged in 2024-07, with the labels that each got.

#1988 attempt to fix jenkins builds
  _delphi_utils_python/setup.py
  claims_hosp/setup.py
  doctor_visits/setup.py
Labels: bug, release-blocking, devops

#1992 chore: sync prod->main
  .bumpversion.cfg
  _delphi_utils_python/.bumpversion.cfg
  _delphi_utils_python/delphi_utils/__init__.py
  _delphi_utils_python/setup.py
  changehc/version.cfg
  claims_hosp/version.cfg
  doctor_visits/version.cfg
  google_symptoms/version.cfg
  hhs_hosp/version.cfg
  nchs_mortality/version.cfg
  quidel_covidtest/version.cfg
  sir_complainsalot/version.cfg
Labels: chore

#2003 avoid linking keywords in PR template
  .github/pull_request_template.md
Labels: bug, documentation
